---
abstract: 'mod_cluster extension to Starman web server'
author:
  - 'Roman Jurkov <winfinit@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Starman-ModCluster
no_index:
  directory:
    - t
    - inc
requires:
  Net::MCMP: 0
  Starman: 0
  Text::SimpleTable: 0
version: 0.02
